% -------------------------------------------------------------------------
% merge.m 
%
% -------------------------------------------------------------------------
% Description:
%
% It copies all files generated by loci.m for every single animal experiment
% and merges them into a common folder that represents the complete kinematic
% information of the corresponding experimental situation (genotype,
% stimulus intensity, etc.). That is useful as a means of centralizing and
% tidying up the data for subsequent analysis.
% If preferred, one can still focus on only one particular trajectory.
% -------------------------------------------------------------------------

clear
close all

% ------------------------------------------------------------------------
% Directories
% dirGo='D:\DATA\DnD\MoviesExportedImages\DnD1\Collaboration\nonWillistoniGroup\D_ananassae\spiracleblocked\';
% dirFinal='C:/Users/dkim/Dropbox (CRG)/Research/ProcessingData/SimpleTrackerData/DnD/Postprocessing/ExptCond/CollabDidac/nonwillistoniGroup/D_ananassae/D_ananassae_spiracleblocked/allTrials/';

dirGo='/Users/daeyeonkim/Documents/Box Sync/MATLAB/projects/DnD/data/sample/';
dirFinal='/Users/daeyeonkim/Documents/Box Sync/MATLAB/projects/DnD/data/sample/trackingData/';

mkdir(dirFinal);
cd(dirGo);

%filesArray=dir(strcat(dirGo,'s*'));
%filesArray=dir(strcat(dirGo,'CS*'));
%filesArray=dir(strcat(dirGo,'spiracle*'));
filesArray=dir(strcat(dirGo,'sample*'));

maxFolder=length(filesArray);

for folder=1:maxFolder

cd(dirGo)
folderName=filesArray(folder).name;
cd(folderName);

% Files to copy
% positions
destination1=strcat(dirFinal,'trackingData', num2str(sprintf('%03d',folder)),'.mat');
destination2=strcat(dirFinal,'traj', num2str(sprintf('%03d',folder)),'.jpeg');
destination3=strcat(dirFinal,'calibration', num2str(sprintf('%03d',folder)),'.jpeg');
destination4=strcat(dirFinal,'depthOverTime', num2str(sprintf('%03d',folder)),'.jpeg');
%
% ashape1, 2 and 3 are not copied yet since they are quite heavy and we are
% not going to use them yet.
%

% Files and location to paste
copyfile('trackingData.mat',destination1);
copyfile('traj.jpeg',destination2);
copyfile('calibration.jpeg',destination3);
copyfile('depthOverTime.jpeg',destination4);

end

% dirOut='/Users/agomez/Desktop/';
% cd(dirOut);

